import { Geist, Geist_Mono } from 'next/font/google'
import Head from 'next/head'
import React from 'react'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
  metaTitle,
}: {
  children: React.ReactNode
  metaTitle: string
}) {
  return (
    <div>
      <Head>
        <title>Next.js App - {metaTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}
      >
        <header className="bg-blue-600 text-white p-4">
          <div className="container mx-auto flex justify-between">
            <h1 className="text-xl font-bold">Next.js App</h1>
            <ul className="flex space-x-4">
              <Link href={'/'}>
                <li>Home</li>
              </Link>
              <Link href={'/about'}>
                <li>About</li>
              </Link>
              <Link href={'/note/server'}>
                <li>Notes</li>
              </Link>
            </ul>
          </div>
        </header>
        <main className="flex-1 container mx-auto p-4">{children}</main>
        <footer className="bg-gray-800 text-white p-4 text-center">
          <p>&copy;{new Date().getFullYear()} My Personal Website</p>
        </footer>
      </div>
    </div>
  )
}
